sudo: false
language: java
jdk:
- openjdk8
cache:
  directories:
  - $HOME/.m2
before_install:
# install the gwtbootstrap5 library before we build the extras
- git clone https://github.com/gwtbootstrap5/gwtbootstrap5.git
- cd gwtbootstrap5
- mvn install -DskipTests=true -DdryRun=true
- cd ..
install: true
script:
- mvn clean install -DdryRun=true -Dlicense.failOnMissingHeader=true -Dlicense.failOnNotUptodateHeader=true
after_success:
- .utility/deploy.sh 
- .utility/update_site_apidocs.sh
- .utility/update_demo_site.sh
